name: pudl
channels:
  - defaults
  - conda-forge
dependencies:
  - codecov
  - coverage
  - dbfread
  - fastparquet
  - jupyter
  - jupyterlab
  - matplotlib
  - nbval
  - networkx>=2.2
  - numpy
  - pandas>=0.24
  - pip
  - psycopg2
  - pyarrow
  - pytest
  - pytest-cov
  - python>=3.7
  - python-snappy
  - pyyaml
  - scikit-learn>=0.20
  - scipy
  - sqlalchemy>=1.3.0
  # conda-forge only:
  - datapackage
  - goodtables
  - tableschema
  - timezonefinder
  - pip:
    - sqlalchemy-postgres-copy
